# Generated by Django 4.2.11 on 2024-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_issue_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Opened"), (2, "In progress"), (3, "Closed")]
            ),
        ),
    ]
